export { default as Home } from './Home'
export { default as About } from './About'
export { default as BMI } from './BMI'
export { default as Cicilan } from './Cicilan'
export { default as PPN } from './PPN'
export { default as NotFound } from './NotFound'